[server]
host = "localhost"
port = 8080
name = "mecdn"

[whitelist]
url = "https://mecdn.mcserverx.com/gh/ahmr-bot/MECDN-WhiteList/master/list.txt"
update_interval = "5m"

# 配置需要代理的域名和对应的路径
[[proxy]]
domain = "a.com"
path = "/a"
[[proxy]]
domain = "b.com"
path = "/b/article"

[debug]
gin_mode = "release"