[server]
host = "localhost"
port = 8080
name = "Five CDN Turbo V1.0"

[whitelist]
url = "https://mecdn.mcserverx.com/gh/ahmr-bot/MECDN-WhiteList/master/list.txt"
update_interval = "1s"

# 配置需要代理的域名和对应的路径
[[proxy]]
domain = "a.com"
path = "/a"
[[proxy]]
domain = "b.com"
path = "/b/article"

[debug]
debug= false