[server]
host = "localhost"
port = 8080
name = "中国香港"
powered_by = "Five CDN Turbo V1.3"

[whitelist]
enabled = false
url = "https://mecdn.mcserverx.com/gh/ahmr-bot/MECDN-WhiteList/master/list.txt"
update_interval = "5m"

# 配置需要代理的域名和对应的路径
[[proxy]]
domain = "raw.cdn.mcserverx.top"
path = "/gh"
[[proxy]]
domain = "unpkg.com"
path = "/npm"

[cors]
allow_all_origins = true
# 此项为 true 时，下方无效
allow_origins = ["http://localhost:8080", "http://example.com"]
allow_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allow_headers = ["Content-Type", "Authorization"]
allow_credentials = false
expose_headers = []

[debug]
debug= false