[server]
host = "localhost"
port = 8081
name = "广东移动"
powered_by = "Five CDN Turbo V1.0"

[whitelist]
enabled = true
url = "https://mecdn.mcserverx.com/gh/ahmr-bot/MECDN-WhiteList/master/list.txt"
update_interval = "5m"

# 配置需要代理的域名和对应的路径
[[proxy]]
domain = "a.com"
path = "/a"
[[proxy]]
domain = "b.com"
path = "/b/article"

[cors]
allow_all_origins = true
# 此项为 true 时，下方无效
allow_origins = ["http://localhost:8080", "http://example.com"]
allow_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allow_headers = ["Content-Type", "Authorization"]
allow_credentials = false
expose_headers = []

[debug]
debug= false